baseurl                  = "/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "helene"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    homepage             = "start"                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = "helene hahn personal visiting card"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "helene"

[[params.mainMenu]]
    link = "/works"
    text = "works"

[[params.mainMenu]]
    link = "/talks"
    text = "talks"

[[params.mainMenu]]
    link = "/whois"
    text = "who is helene?"

[[params.mainMenu]]
    link = "/contact"
    text = "contact"

[imaging]
    quality = 75

[blackfriday]
  hrefTargetBlank = true
  noopenerLinks = true
